<?php
/**
 * @see Chronopost_Chronorelais_Block_Adminhtml_Notification
 */
?>
<?php $notifications = $this->getNotifications();?>
<?php if ($this->canShow() && count($notifications) > 0): ?>
<script type="text/javascript">
//<![CDATA[
    var messagePopupClosed = false;
    function openMessagePopup() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        $('message-popup-window').addClassName('show');
    }

    function closeMessagePopup() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
    }

    Event.observe(window, 'load', openMessagePopup);
    Event.observe(window, 'keyup', function(evt) {
        if(messagePopupClosed) return;
        var code;
        if (evt.keyCode) code = evt.keyCode;
        else if (evt.which) code = evt.which;
        if (code == Event.KEY_ESC) {
            closeMessagePopup();
        }
    });
//]]>
</script>
<div id="message-popup-window-mask" style="display:none;"></div>
<div id="message-popup-window" class="message-popup">
    <div class="message-popup-head">
        <a href="#" onclick="closeMessagePopup(); return false;" title="Close"><span><?php echo $this->__('close'); ?></span></a>
        <h2>Chronopost vous informe :</h2>
    </div>
    <div class="message-popup-content">
        <div class="message">
            <span class="message-icon message-notice" style="background-image:url(<?php echo $this->getSeverityIconsUrl() ?>);">Notice</span>
            <?php foreach($notifications as $notif): ?>
            <p class="message-text">
                <?php
                switch($notif) {
                    case 'quickcost_not_available':
                        echo 'Le quickcost est momentanément indisponible, les prix renseignés dans la grille tarifaire sont appliqués.
                            <br />
                            Veuillez les vérifier.';
                    break;

                    case 'new_version':
                        echo 'Une nouvelle version du module Chronopost est disponible.';
                        echo 'Vous pouvez la télécharger <a href="http://www.magentocommerce.com/magento-connect/chronopost.html" target="_blank">ici</a>';
                    break;
                }
                ?>
            </p>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>
